use crate::epiano::epiano_preset::EpianoPreset;

pub fn get_epiano_presets() -> Vec<EpianoPreset> {
    return vec![
        EpianoPreset {
            id: 0,
            name: "Tremolo".to_string(),
            envelope_decay: 0.500,
            envelope_release: 0.500,
            hardness: 0.500,
            treble_boost: 0.500,
            modulation: 0.750,
            lfo_rate: 0.650,
            velocity_sense: 0.250,
            stereo_width: 0.500,
            polyphony: 0.50,
            fine_tuning: 0.500,
            random_tuning: 0.246,
            overdrive: 0.000,
        },
        EpianoPreset {
            id: 0,
            name: "Bright".to_string(),
            envelope_decay: 0.500,
            envelope_release: 0.500,
            hardness: 1.000,
            treble_boost: 0.800,
            modulation: 0.500,
            lfo_rate: 0.650,
            velocity_sense: 0.250,
            stereo_width: 0.500,
            polyphony: 0.50,
            fine_tuning: 0.500,
            random_tuning: 0.146,
            overdrive: 0.500,
        },
        EpianoPreset {
            id: 0,
            name: "Mellow".to_string(),
            envelope_decay: 0.500,
            envelope_release: 0.500,
            hardness: 0.000,
            treble_boost: 0.000,
            modulation: 0.500,
            lfo_rate: 0.650,
            velocity_sense: 0.250,
            stereo_width: 0.500,
            polyphony: 0.50,
            fine_tuning: 0.500,
            random_tuning: 0.246,
            overdrive: 0.000,
        },
        EpianoPreset {
            id: 0,
            name: "Autopan".to_string(),
            envelope_decay: 0.500,
            envelope_release: 0.500,
            hardness: 0.500,
            treble_boost: 0.500,
            modulation: 0.250,
            lfo_rate: 0.650,
            velocity_sense: 0.250,
            stereo_width: 0.500,
            polyphony: 0.50,
            fine_tuning: 0.500,
            random_tuning: 0.246,
            overdrive: 0.000,
        },
    ]
}